title: Luke's Page
tagline: "I am a great believer in luck, and I find the harder I work the more I have of it."
email: lacaffar@ncsu.edu
description: >-
  This is my personal website I built; hope you enjoy!
baseurl: "" # leave empty if deploying to https://<username>.github.io
url: "https://lacaffar.github.io"

twitter_username: yourtwitter
github_username: lacaffar

# Theme and plugins
remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-remote-theme


# Navigation (optional for this theme)
nav:
  - name: "Home"
    url: "/"
  - name: "Blog"
    url: "/blog"
  - name: "Web Scraper"
    url: "/scraper"
  - name: "Resume"
    url: "/resume"

# SCSS
sass:
  sass_dir: css