title: Your Name's Website
email: your-email@example.com
description: >- 
  This is my personal website with blog, web scraper, and resume.
baseurl: ""
url: "https://lacaffar.github.io"
twitter_username: yourtwitter
github_username: lacaffar

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Navigation links
nav:
  - name: "Home"
    url: "/"
  - name: "Blog"
    url: "/blog"
  - name: "Web Scraper"
    url: "/scraper"
  - name: "Resume"
    url: "/resume"