title: Luke Caffarey
email: lacaffar@ncsu.edu
description: >- 
  This is my personal website I built; hope you enjoy!
baseurl: ""
url: "https://lacaffar.github.io"
twitter_username: yourtwitter
github_username: lacaffar

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Navigation links
nav:
  - name: "Home"
    url: "/"
  - name: "Blog"
    url: "/blog"
  - name: "Web Scraper"
    url: "/scraper"
  - name: "Resume"
    url: "/resume"

# compile that scss intro animation into css directory
sass:
  sass_dir: css